"""Persistence: SQLite schema, session handling, and artifact storage."""

from crucible.store.artifacts import ArtifactRef, ArtifactStore
from crucible.store.db import (
    DEFAULT_DB_URL,
    ensure_parent_dir,
    init_db,
    make_engine,
    make_session_factory,
    session_scope,
)
from crucible.store.models import (
    AppMap,
    Base,
    CaseStatus,
    Classification,
    Execution,
    Finding,
    FindingStatus,
    LLMSpanRow,
    Memory,
    Run,
    RunStatus,
    Severity,
    Target,
    TestCase,
    TestPlan,
    Verdict,
    VerdictDecision,
    new_id,
)

__all__ = [
    "DEFAULT_DB_URL",
    "AppMap",
    "ArtifactRef",
    "ArtifactStore",
    "Base",
    "CaseStatus",
    "Classification",
    "Execution",
    "Finding",
    "FindingStatus",
    "LLMSpanRow",
    "Memory",
    "Run",
    "RunStatus",
    "Severity",
    "Target",
    "TestCase",
    "TestPlan",
    "Verdict",
    "VerdictDecision",
    "ensure_parent_dir",
    "init_db",
    "make_engine",
    "make_session_factory",
    "new_id",
    "session_scope",
]
